spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5515/account_service_database
    username: dlr
    password:
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081
